name: Create calendar version tag
run-name: Create tag for ${{ github.sha }}

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-tags: true
        persist-credentials: false
    - name: Bump version number
      run: |
        git config --global --add safe.directory /github/workspace

        prev_tag="$(git describe --abbrev=0 --tags)"
        if ! [[ $prev_tag =~ ^([0-9]{4})\.([0-9]{1,2})\.([0-9]+)$ ]]; then
          echo "Invalid prev_tag format. Expected YYYY.M.P or YYYY.MM.P"
          exit 2
        fi

        prev_year="${BASH_REMATCH[1]}"
        prev_month="${BASH_REMATCH[2]}"
        prev_patch="${BASH_REMATCH[3]}"

        curr_year="$(date +%Y)"
        curr_month="$(date +%-m)"  # Without leading zero

        if [ "$curr_year" = "$prev_year" ] && [ "$curr_month" = "$prev_month" ]; then
          new_patch=$((prev_patch + 1))
          new_tag="${curr_year}.${curr_month}.${new_patch}"
        else
          new_tag="${curr_year}.${curr_month}.0"
        fi

        git tag "${new_tag}" -m ""
        git push origin "${new_tag}"
